// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/function/proto/function.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteFunctionRequest represents a request to execute a function
type ExecuteFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Event         *CloudEvent            `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteFunctionRequest) Reset() {
	*x = ExecuteFunctionRequest{}
	mi := &file_internal_function_proto_function_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionRequest) ProtoMessage() {}

func (x *ExecuteFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_function_proto_function_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionRequest) Descriptor() ([]byte, []int) {
	return file_internal_function_proto_function_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteFunctionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecuteFunctionRequest) GetEvent() *CloudEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// ExecuteFunctionResponse represents the response from a function execution
type ExecuteFunctionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ExecuteFunctionResponse_Error
	//	*ExecuteFunctionResponse_Data
	Result        isExecuteFunctionResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteFunctionResponse) Reset() {
	*x = ExecuteFunctionResponse{}
	mi := &file_internal_function_proto_function_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionResponse) ProtoMessage() {}

func (x *ExecuteFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_function_proto_function_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionResponse) Descriptor() ([]byte, []int) {
	return file_internal_function_proto_function_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteFunctionResponse) GetResult() isExecuteFunctionResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteFunctionResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ExecuteFunctionResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *ExecuteFunctionResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Result.(*ExecuteFunctionResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isExecuteFunctionResponse_Result interface {
	isExecuteFunctionResponse_Result()
}

type ExecuteFunctionResponse_Error struct {
	Error string `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type ExecuteFunctionResponse_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ExecuteFunctionResponse_Error) isExecuteFunctionResponse_Result() {}

func (*ExecuteFunctionResponse_Data) isExecuteFunctionResponse_Result() {}

// CloudEvent represents a CloudEvents event
type CloudEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	SpecVersion     string                 `protobuf:"bytes,3,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Time            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	DataContentType string                 `protobuf:"bytes,6,opt,name=data_content_type,json=dataContentType,proto3" json:"data_content_type,omitempty"`
	DataSchema      string                 `protobuf:"bytes,7,opt,name=data_schema,json=dataSchema,proto3" json:"data_schema,omitempty"`
	Subject         string                 `protobuf:"bytes,8,opt,name=subject,proto3" json:"subject,omitempty"`
	Data            []byte                 `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	Extensions      map[string]string      `protobuf:"bytes,10,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CloudEvent) Reset() {
	*x = CloudEvent{}
	mi := &file_internal_function_proto_function_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudEvent) ProtoMessage() {}

func (x *CloudEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_function_proto_function_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudEvent.ProtoReflect.Descriptor instead.
func (*CloudEvent) Descriptor() ([]byte, []int) {
	return file_internal_function_proto_function_proto_rawDescGZIP(), []int{2}
}

func (x *CloudEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CloudEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CloudEvent) GetSpecVersion() string {
	if x != nil {
		return x.SpecVersion
	}
	return ""
}

func (x *CloudEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CloudEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *CloudEvent) GetDataContentType() string {
	if x != nil {
		return x.DataContentType
	}
	return ""
}

func (x *CloudEvent) GetDataSchema() string {
	if x != nil {
		return x.DataSchema
	}
	return ""
}

func (x *CloudEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CloudEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CloudEvent) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

var File_internal_function_proto_function_proto protoreflect.FileDescriptor

const file_internal_function_proto_function_proto_rawDesc = "" +
	"\n" +
	"&internal/function/proto/function.proto\x12\bfunction\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n" +
	"\x16ExecuteFunctionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x05event\x18\x02 \x01(\v2\x14.function.CloudEventR\x05event\"Q\n" +
	"\x17ExecuteFunctionResponse\x12\x16\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\b\n" +
	"\x06result\"\x9b\x03\n" +
	"\n" +
	"CloudEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12!\n" +
	"\fspec_version\x18\x03 \x01(\tR\vspecVersion\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12*\n" +
	"\x11data_content_type\x18\x06 \x01(\tR\x0fdataContentType\x12\x1f\n" +
	"\vdata_schema\x18\a \x01(\tR\n" +
	"dataSchema\x12\x18\n" +
	"\asubject\x18\b \x01(\tR\asubject\x12\x12\n" +
	"\x04data\x18\t \x01(\fR\x04data\x12D\n" +
	"\n" +
	"extensions\x18\n" +
	" \x03(\v2$.function.CloudEvent.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012k\n" +
	"\x0fFunctionService\x12X\n" +
	"\x0fExecuteFunction\x12 .function.ExecuteFunctionRequest\x1a!.function.ExecuteFunctionResponse\"\x00B8Z6github.com/julianshen/mycelium/internal/function/protob\x06proto3"

var (
	file_internal_function_proto_function_proto_rawDescOnce sync.Once
	file_internal_function_proto_function_proto_rawDescData []byte
)

func file_internal_function_proto_function_proto_rawDescGZIP() []byte {
	file_internal_function_proto_function_proto_rawDescOnce.Do(func() {
		file_internal_function_proto_function_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_function_proto_function_proto_rawDesc), len(file_internal_function_proto_function_proto_rawDesc)))
	})
	return file_internal_function_proto_function_proto_rawDescData
}

var file_internal_function_proto_function_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_function_proto_function_proto_goTypes = []any{
	(*ExecuteFunctionRequest)(nil),  // 0: function.ExecuteFunctionRequest
	(*ExecuteFunctionResponse)(nil), // 1: function.ExecuteFunctionResponse
	(*CloudEvent)(nil),              // 2: function.CloudEvent
	nil,                             // 3: function.CloudEvent.ExtensionsEntry
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_internal_function_proto_function_proto_depIdxs = []int32{
	2, // 0: function.ExecuteFunctionRequest.event:type_name -> function.CloudEvent
	4, // 1: function.CloudEvent.time:type_name -> google.protobuf.Timestamp
	3, // 2: function.CloudEvent.extensions:type_name -> function.CloudEvent.ExtensionsEntry
	0, // 3: function.FunctionService.ExecuteFunction:input_type -> function.ExecuteFunctionRequest
	1, // 4: function.FunctionService.ExecuteFunction:output_type -> function.ExecuteFunctionResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_function_proto_function_proto_init() }
func file_internal_function_proto_function_proto_init() {
	if File_internal_function_proto_function_proto != nil {
		return
	}
	file_internal_function_proto_function_proto_msgTypes[1].OneofWrappers = []any{
		(*ExecuteFunctionResponse_Error)(nil),
		(*ExecuteFunctionResponse_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_function_proto_function_proto_rawDesc), len(file_internal_function_proto_function_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_function_proto_function_proto_goTypes,
		DependencyIndexes: file_internal_function_proto_function_proto_depIdxs,
		MessageInfos:      file_internal_function_proto_function_proto_msgTypes,
	}.Build()
	File_internal_function_proto_function_proto = out.File
	file_internal_function_proto_function_proto_goTypes = nil
	file_internal_function_proto_function_proto_depIdxs = nil
}
